services:
  - type: web
    name: edo-ldpr-api
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        scope: build,runtime
      - key: FLASK_SECRET
        scope: build,runtime
